# Generated by Django 3.2.6 on 2022-05-29 22:51

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Course name')),
                ('company', models.CharField(max_length=150, verbose_name='Company name')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('certificate', models.FileField(null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='course')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CourseSectionsModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Course name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('courses', djongo.models.fields.ArrayReferenceField(blank=True, db_column='courses', null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursesmodel')),
            ],
            options={
                'verbose_name': 'Course Section',
                'verbose_name_plural': 'Courses Section',
                'db_table': 'courses-section',
            },
        ),
    ]
