# Generated by Django 3.2.6 on 2022-02-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesectionsmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursesmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
