# Generated by Django 3.2.6 on 2022-06-18 15:55

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_coursesectionsmodel_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesectionsmodel',
            name='courses',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='course.coursesmodel'),
        ),
    ]
