# Generated by Django 3.2.6 on 2023-08-31 03:52

import apps.information.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformationModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('profession', models.CharField(max_length=100, verbose_name='Profession')),
                ('about', models.CharField(max_length=250, verbose_name='About Me')),
                ('profile_photo', models.CharField(max_length=250, verbose_name='Profile Photo')),
                ('contact_info', djongo.models.fields.EmbeddedField(model_container=apps.information.models.ContactInfoModel)),
                ('contact_social', djongo.models.fields.ArrayField(model_container=apps.information.models.ContactSocialModel)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Personal Information',
                'verbose_name_plural': "Personal Information's",
                'db_table': 'information',
            },
        ),
    ]
