# Generated by Django 3.2.6 on 2022-02-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformationmodel',
            name='about',
            field=models.CharField(default='', max_length=250, verbose_name='About Me'),
            preserve_default=False,
        ),
    ]
