# Generated by Django 3.2.6 on 2022-02-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodels',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Job Description'),
        ),
    ]
