# Generated by Django 3.2.6 on 2022-02-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
