# Generated by Django 3.2.6 on 2022-01-30 21:14

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModels',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=100, verbose_name='Degree')),
                ('collage', models.CharField(max_length=100, verbose_name='Collage')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('currently', models.BooleanField(default=False, verbose_name='Currently')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='education')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'db_table': 'educations',
            },
        ),
    ]
