name: CV CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "GitHubActions" ]

env:
  python-version: '3.10'

jobs:
  mail-service-up:
    services:
      maildev:
        image: maildev/maildev
        ports:
          - "1080:1080"
          - "1025:1025"

  build:
    runs-on: ubuntu-22.04.1
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/requirements-dev.txt'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r subdirectory/requirements-dev.txt

  testing:
    runs-on: ubuntu-22.04.1
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run Tests
      run: python manage.py test
