name: CV CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]
    types: ["opened", "synchronize"]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Save build dir
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
          retention-days: 1

  testing:
    needs: ['build']
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'
      - name: Print Package
        run: pip freeze
      - name: Download dist package
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Run Tests
        run: python manage.py test