name: CV CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]
    types: ["opened", "synchronize"]

env:
  python-version: '3.10'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/requirements.txt'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt

  testing:
    needs: ['build']
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run Tests
      run: python manage.py test
